server:
  port: 8000
#  context-path: userservice
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                                     # 指定数据源
    platform: h2                                  # 指定数据源类型
    schema: classpath:schema.sql                  # 指定h2数据库的建表脚本
    data: classpath:data.sql                      # 指定h2数据库的数据脚本
  application:
    name: microservice-provide-user               # 注册到eureka server的服务名
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true                       # 将自己的IP注册到eureka server上，默认false
    metadata-map:
      # 自定义元数据，key/value可以随便写
      my-metadata: 我自定义的元数据
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace


info:
  app:
    name: microservice-provide-user-my-metadata
    encoding: UTF-8
    java:
      source: 1.8.0_171
      target: 1.8.0_171